version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: startimage
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/hello_db
      SPRING_DATASOURCE_USERNAME: hello_user
      SPRING_DATASOURCE_PASSWORD: hello_pass
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_DB: hello_db
      POSTGRES_USER: hello_user
      POSTGRES_PASSWORD: hello_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
